# Generated by Django 5.0.7 on 2024-07-16 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
